#!/usr/bin/python3

"""Module that factorize as many numbers as possible

 into a product of two smaller numbers."""

from sys import argv





def factorize(n):

    """"print a simple descomposition of an integer > 1"""

    i = 2



    if n < 2:

        return

    print()

    print(n, "<- n-bef")

    while n % i:

        i += 1

    print("{:.0f}={:.0f}*{:.0f}".format(n, n / i, i))

    print(n, "<- n-aft")

    print()



if len(argv) != 2:

    exit()



try:

    with open(argv[1]) as file:

        line = file.readline()



        while line != "":

           n = int(line.split('\n')[0])

            factorize(n)

            line = file.readline()

except:

    ...
